### ISSUE TITLE
Three Known Validators In Config File Are Offline / Dead

### ISSUE THREAD

**Issue by bonedaddy** [mvines/sosh#1]
The three known mainnet validators listed [here](https://github.com/mvines/sosh/blob/51b2e79506ea9aa10627d20d2411bffbb9e4a0cf/service-env.sh#L57-L59) have  0 active stake, and are essentially offline

**Comment by mvines** [comment]
Those validators have no stake deliberately, and are very rarely offline.

**Comment by bonedaddy** [comment]
Ah makes sense, thanks for clarifying :+1:
